/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\meteor.glb 
Author: Maxim Mavrichev (https://sketchfab.com/mvrc.art)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/meteor-d3a5a7e9a7d24b76841bf0f49d56a5f3
Title: Meteor
*/

import React, { useRef } from "react";
import { useGLTF, useScroll } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export const FLOOR_HEIGHT = 2.3;
export const NB_FLOORS = 3;

export function Meteor(props) {
  const { nodes, materials } = useGLTF("/models/meteor.glb");
  const ref = useRef();
  const scroll = useScroll();

  useFrame(() => {
    if (!ref.current) return;
    const targetY = -FLOOR_HEIGHT * (NB_FLOORS - 1) * scroll.offset;
    ref.current.position.y = targetY;
    ref.current.rotation.y += 0.01;
  });

  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.Material}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/meteor.glb");
